#!/usr/bin/env bash
# reconstruction-init.sh — Initialize the reconstruction project directory for a target.
# Usage: reconstruction-init.sh --target-id <id> --reconstruction-root <path> [--arch <x86_64|arm64>]
set -euo pipefail

TARGET_ID=""
RECON_ROOT=""
ARCH="x86_64"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target-id) TARGET_ID="$2"; shift 2 ;;
    --reconstruction-root) RECON_ROOT="$2"; shift 2 ;;
    --arch) ARCH="$2"; shift 2 ;;
    *) shift ;;
  esac
done

[[ -z "$TARGET_ID" || -z "$RECON_ROOT" ]] && {
  echo "Usage: reconstruction-init.sh --target-id <id> --reconstruction-root <path>" >&2
  exit 1
}

echo "Initializing reconstruction project at $RECON_ROOT ..."

# Create directory structure
mkdir -p "$RECON_ROOT"/{include/common,src,third_party,stubs,tests/harness,build/{lib,bin}}

# Create .gitignore
cat > "$RECON_ROOT/.gitignore" <<'EOF'
build/
*.o
*.d
CMakeCache.txt
CMakeFiles/
cmake_install.cmake
Makefile
EOF

# Create CMakeLists.txt
cat > "$RECON_ROOT/CMakeLists.txt" <<EOF
cmake_minimum_required(VERSION 3.20)
project(${TARGET_ID}_reconstruction C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

if(CMAKE_C_COMPILER_ID MATCHES "Clang")
  add_compile_options(
    -Wno-error=implicit-function-declaration
    -Wno-int-conversion
    -Wno-incompatible-pointer-types
    -Wno-pointer-sign
  )
endif()

# Debug by default for reconstruction
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Debug)
endif()

# Include directories
include_directories(include)

# Collect sources
file(GLOB RECON_SOURCES CONFIGURE_DEPENDS "src/*.c")
file(GLOB STUB_SOURCES CONFIGURE_DEPENDS "stubs/*.c")

# Main reconstruction library
add_library(reconstruction STATIC \${RECON_SOURCES} \${STUB_SOURCES})
target_link_libraries(reconstruction dl)

# Test harness
file(GLOB TEST_SOURCES "tests/*_test.c")
if(TEST_SOURCES)
  add_executable(test_runner tests/harness/test_runner.c \${TEST_SOURCES})
  target_link_libraries(test_runner reconstruction)
endif()

# Third-party subdirectories (populated by pipeline)
# file(GLOB THIRD_PARTY_DIRS "third_party/*/CMakeLists.txt")
# foreach(tp \${THIRD_PARTY_DIRS})
#   get_filename_component(tp_dir \${tp} DIRECTORY)
#   add_subdirectory(\${tp_dir})
# endforeach()
EOF

# Create placeholder files
cat > "$RECON_ROOT/include/common/types.h" <<'EOF'
/* types.h — Exported types and structs from Ghidra analysis.
 * Auto-generated by the headless-ghidra pipeline. */
#ifndef COMMON_TYPES_H
#define COMMON_TYPES_H

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <sys/types.h>

/* Baseline exported types will extend these common Ghidra aliases. */
typedef uint8_t byte;
typedef uint8_t undefined;
typedef uint8_t undefined1;
typedef uint16_t undefined2;
typedef uint32_t undefined4;
typedef uint64_t undefined8;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned long ulong;
typedef int BOOL;

#endif /* COMMON_TYPES_H */
EOF

cat > "$RECON_ROOT/include/common/constants.h" <<'EOF'
/* constants.h — Exported constants from Ghidra analysis.
 * Auto-generated by the headless-ghidra pipeline. */
#ifndef COMMON_CONSTANTS_H
#define COMMON_CONSTANTS_H

/* Constants will be populated by the baseline export phase. */

#endif /* COMMON_CONSTANTS_H */
EOF

cat > "$RECON_ROOT/stubs/original_bridge.h" <<'EOF'
/* original_bridge.h — Bridge declarations for unreconstructed functions. */
#ifndef ORIGINAL_BRIDGE_H
#define ORIGINAL_BRIDGE_H

void bridge_init(const char* original_path);
void bridge_cleanup(void);

#endif /* ORIGINAL_BRIDGE_H */
EOF

cat > "$RECON_ROOT/stubs/original_bridge.c" <<'EOF'
/* original_bridge.c — Bridge unreconstructed functions to original binary. */
#include "original_bridge.h"
#include <dlfcn.h>
#include <stdio.h>

static void* original_handle = NULL;

void bridge_init(const char* original_path) {
    original_handle = dlopen(original_path, RTLD_NOW);
    if (!original_handle) {
        fprintf(stderr, "bridge_init: failed to load %s: %s\n",
                original_path, dlerror());
    }
}

void bridge_cleanup(void) {
    if (original_handle) {
        dlclose(original_handle);
        original_handle = NULL;
    }
}
EOF

# Create stub manifest
cat > "$RECON_ROOT/stubs/stub_manifest.yaml" <<EOF
bridge_strategy: "dlopen"
original_binary: ""
stubs: []
EOF

# Create third-party manifest
cat > "$RECON_ROOT/third_party/third-party-manifest.yaml" <<EOF
# Third-party library manifest — populated from P2 reviewed library notes
# in evidence-candidates.md, or from legacy library-identification.yaml replays
libraries: []
EOF

# Create test harness
cat > "$RECON_ROOT/tests/harness/test_runner.c" <<'EOF'
/* test_runner.c — Unified test entry point for reconstruction verification. */
#include <stdio.h>
#include <stdlib.h>

/* Individual test functions are declared by each *_test.c file. */

int main(int argc, char* argv[]) {
    printf("reconstruction test runner\n");
    printf("run individual test binaries for per-function verification\n");
    return 0;
}
EOF

# Create reconstruction-manifest.yaml
NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%SZ")
cat > "$RECON_ROOT/reconstruction-manifest.yaml" <<EOF
schema_version: 1
target_id: "$TARGET_ID"
original_binary: ""
created_at: "$NOW"
updated_at: "$NOW"

build:
  cmake_minimum_version: "3.20"
  compiler: "gcc"
  standard: "c11"
  target_arch: "$ARCH"
  build_type: "Debug"
  extra_flags: []
  link_libraries: []

third_party: []

functions: []

stubs:
  total_stubbed: 0
  functions: []

dependencies:
  system_libraries: ["libc"]
  reconstructed_headers: ["include/common/types.h"]
EOF

echo "Reconstruction project initialized at $RECON_ROOT"
echo "{\"status\":\"initialized\",\"target_id\":\"$TARGET_ID\",\"path\":\"$RECON_ROOT\"}"
