#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${SKILL_DIR}/.." && pwd)"
RUNNER="${SCRIPT_DIR}/run-headless-analysis.sh"

TARGET_ID="placeholder-repro"
BINARY_PATH=""
SELECTED_FUNCTION="entry@00100000"
WORK_ROOT="${REPO_ROOT}/.work/repros/placeholder-selected-decompilation"

usage() {
  cat <<'EOF'
Replay the selected-decompilation placeholder failure path without relying on a
live Ghidra export.

The script bootstraps a fake analyzeHeadless wrapper that emits a
decompiled-output.md containing one placeholder-only function section, then runs
the real run-headless-analysis.sh --action decompile-selected entrypoint.

Options:
  --work-root PATH          Scratch root for the replay.
  --target-id ID            Target id to use inside the scratch artifacts tree.
  --binary PATH             Existing binary path to satisfy runner validation.
                            Required; point this at your mock ls verification
                            binary or another local executable.
  --selected-function ID    Selected function identity, for example entry@00100000.
  -h, --help                Show this help.
EOF
}

require_file() {
  local path="$1"
  local reason="$2"
  if [[ ! -f "${path}" ]]; then
    printf 'Missing expected file: %s\nReason: %s\n' "${path}" "${reason}" >&2
    exit 1
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --work-root)
      WORK_ROOT="${2:-}"
      shift 2
      ;;
    --target-id)
      TARGET_ID="${2:-}"
      shift 2
      ;;
    --binary)
      BINARY_PATH="${2:-}"
      shift 2
      ;;
    --selected-function)
      SELECTED_FUNCTION="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "${BINARY_PATH}" ]]; then
  printf 'Missing --binary PATH. Point this at your mock ls verification binary.\n' >&2
  exit 1
fi

if [[ ! -f "${BINARY_PATH}" ]]; then
  printf 'Binary not found: %s\n' "${BINARY_PATH}" >&2
  exit 1
fi

FUNCTION_NAME="${SELECTED_FUNCTION%@*}"
if [[ -z "${FUNCTION_NAME}" || "${FUNCTION_NAME}" == "${SELECTED_FUNCTION}" ]]; then
  printf 'Selected function must include name@address: %s\n' "${SELECTED_FUNCTION}" >&2
  exit 1
fi

WORK_ROOT="$(mkdir -p "${WORK_ROOT}" && cd "${WORK_ROOT}" && pwd -P)"
WORKSPACE_ROOT="${WORK_ROOT}/workspace"
PROJECT_ROOT="${WORKSPACE_ROOT}/.work/ghidra-projects"
ARTIFACT_ROOT="${WORKSPACE_ROOT}/.work/ghidra-artifacts/${TARGET_ID}"
FAKE_INSTALL_DIR="${WORK_ROOT}/fake-ghidra"
FAKE_ANALYZE_HEADLESS="${FAKE_INSTALL_DIR}/support/analyzeHeadless"
RECON_ROOT="${WORKSPACE_ROOT}/.work/reconstruction/${TARGET_ID}"

rm -rf "${WORK_ROOT}/workspace" "${WORK_ROOT}/fake-ghidra"
mkdir -p "${WORKSPACE_ROOT}" "${PROJECT_ROOT}" "${ARTIFACT_ROOT}" "${FAKE_INSTALL_DIR}/support"

for name in \
  function-names.md \
  imports-and-libraries.md \
  strings-and-constants.md \
  types-and-structs.md \
  xrefs-and-callgraph.md \
  renaming-log.md \
  signature-log.md; do
  cat > "${ARTIFACT_ROOT}/${name}" <<EOF
# ${name}

Seeded baseline artifact for placeholder replay.
EOF
done

cat > "${ARTIFACT_ROOT}/decompiled-output.md" <<EOF
# Decompiled Output

- Target ID: \`${TARGET_ID}\`
- Program: \`$(basename "${BINARY_PATH}")\`
- Generated by: \`ExportAnalysisArtifacts.java\`

## Status

- Stage: \`Baseline Evidence\`
- Decompiled bodies are intentionally blocked in this stage.
EOF

cat > "${FAKE_ANALYZE_HEADLESS}" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

script_name=""
artifact_root=""
target_id=""
action_mode=""
selected_function=""
run_log=""
script_log=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    -postScript)
      script_name="${2:-}"
      artifact_root="${3:-}"
      target_id="${4:-}"
      action_mode="${5:-}"
      selected_function="${6:-}"
      shift 6
      ;;
    -log)
      run_log="${2:-}"
      shift 2
      ;;
    -scriptlog)
      script_log="${2:-}"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

mkdir -p "${artifact_root}" "$(dirname "${run_log}")" "$(dirname "${script_log}")"
printf 'stub analyzeHeadless invoked\n' > "${run_log}"
printf 'stub script log for %s\n' "${script_name}" > "${script_log}"

function_name="${selected_function%@*}"
if [[ -z "${function_name}" || "${function_name}" == "${selected_function}" ]]; then
  function_name="entry"
fi

cat > "${artifact_root}/decompiled-output.md" <<MARKDOWN
# Decompiled Output

- Target ID: \`${target_id}\`
- Program: \`placeholder\`
- Generated by: \`${script_name}\`

### Function 1: \`${function_name}\`

- \`function_identity\`: \`${selected_function}\`
- \`selection_reason\`: \`placeholder_regression_replay\`
- \`role_evidence\`: \`placeholder_replay\`
- \`name_evidence\`: \`placeholder_replay\`
- \`prototype_evidence\`: \`placeholder_replay\`
- \`confidence\`: \`high\`
- \`open_questions\`: \`none\`

\`\`\`c
/* Decompilation unavailable. */
\`\`\`
MARKDOWN
EOF

chmod +x "${FAKE_ANALYZE_HEADLESS}"

printf 'Running placeholder replay under %s\n' "${WORK_ROOT}"
runner_status=0
"${RUNNER}" \
  --action decompile-selected \
  --workspace-root "${WORKSPACE_ROOT}" \
  --project-root "${PROJECT_ROOT}" \
  --artifacts-dir "${ARTIFACT_ROOT}" \
  --install-dir "${FAKE_INSTALL_DIR}" \
  --binary "${BINARY_PATH}" \
  --target-id "${TARGET_ID}" \
  --selected-function "${SELECTED_FUNCTION}" || runner_status=$?

if [[ "${runner_status}" -eq 0 ]]; then
  printf 'Expected decompile-selected to fail for placeholder-only export, but it succeeded.\n' >&2
  exit 1
fi

VERIFY_REPORT="${ARTIFACT_ROOT}/iterations/001/functions/fn_001/verify-report.yaml"
DECOMP_RECORD="${ARTIFACT_ROOT}/iterations/001/functions/fn_001/decompilation-record.yaml"
MATERIALIZED_C="${ARTIFACT_ROOT}/iterations/001/functions/fn_001/decompiled-output/${FUNCTION_NAME}.c"

require_file "${VERIFY_REPORT}" "Placeholder replay must emit a per-function verify report."
require_file "${DECOMP_RECORD}" "Placeholder replay must still emit a decompilation record."
require_file "${MATERIALIZED_C}" "Placeholder replay must materialize the selected function output."

if ! rg -n 'step: "decompilation_export"' "${VERIFY_REPORT}" >/dev/null 2>&1; then
  printf 'verify-report.yaml did not record the decompilation_export step: %s\n' "${VERIFY_REPORT}" >&2
  exit 1
fi
if ! rg -n 'status: "failed"' "${VERIFY_REPORT}" >/dev/null 2>&1; then
  printf 'verify-report.yaml did not mark placeholder export as failed: %s\n' "${VERIFY_REPORT}" >&2
  exit 1
fi
if ! rg -n 'Selected decompilation only exported the unavailable placeholder\.' "${VERIFY_REPORT}" >/dev/null 2>&1; then
  printf 'verify-report.yaml did not retain the placeholder failure reason: %s\n' "${VERIFY_REPORT}" >&2
  exit 1
fi

gate_status=0
ghidra-agent-cli gate check \
  --phase P5 \
  --target "${TARGET_ID}" || gate_status=$?

if [[ "${gate_status}" -eq 0 ]]; then
  printf 'Expected P5 gate to fail for placeholder-only export, but it passed.\n' >&2
  exit 1
fi

printf 'Replay completed as expected.\n'
printf 'Runner exit code: %s\n' "${runner_status}"
printf 'P5 gate exit code: %s\n' "${gate_status}"
printf 'Artifacts: %s\n' "${ARTIFACT_ROOT}"
printf 'Reconstruction root: %s\n' "${RECON_ROOT}"
